/**
 * Clickjacking protection
 * Category: security | Priority: high
 * Verify page cannot be embedded in iframes on other domains
 *
 * Source: https://demoqa.com/
 * Tags: security, clickjacking, x-frame-options
 * Auto-generated by Screener Playwright Crawler
 */

import { test, expect } from '@playwright/test';

test.describe('Clickjacking protection', () => {

  test('Clickjacking protection', async ({ page }) => {
    // Verify page cannot be embedded in iframes on other domains
    await page.evaluate(() => { (() => {
            if (window.top !== window.self) return 'already-framed';
            const meta = document.querySelector('meta[http-equiv="X-Frame-Options"]');
            return meta ? meta.getAttribute('content') : 'no-x-frame-options';
          })() }); // X-Frame-Options or CSP frame-ancestors checked

    // Expected Results:
    // ✓ X-Frame-Options header is DENY or SAMEORIGIN
    // ✓ Or CSP frame-ancestors directive is set
    // ✓ Page cannot be iframed by malicious sites
  });
});
