/**
 * Content Security Policy verification
 * Category: security | Priority: high
 * Verify CSP headers or meta tags are configured
 *
 * Source: https://demoqa.com/
 * Tags: security, csp, xss-prevention
 * Auto-generated by Screener Playwright Crawler
 */

import { test, expect } from '@playwright/test';

test.describe('Content Security Policy verification', () => {

  test('Content Security Policy verification', async ({ page }) => {
    // Verify CSP headers or meta tags are configured
    await page.goto('https://demoqa.com/', { waitUntil: 'domcontentloaded' }); // Page loaded
    await page.evaluate(() => { (() => {
            const meta = document.querySelector('meta[http-equiv="Content-Security-Policy"]');
            return meta ? meta.getAttribute('content') : 'no-csp-meta';
          })() }); // CSP meta tag or header presence checked
    await page.evaluate(() => { (() => {
            try {
              new Function('return 1+1')();
              return 'eval-allowed';
            } catch {
              return 'eval-blocked';
            }
          })() }); // CSP blocks unsafe-eval ('unsafe-eval' not in policy)
    await expect(page.getByText('eval-blocked')).toBeVisible();

    // Expected Results:
    // ✓ CSP is configured (header or meta tag)
    // ✓ Unsafe-inline scripts are blocked
    // ✓ Unsafe-eval is blocked
    // ✓ External script sources are whitelisted
  });
});
