/**
 * HTTPS enforcement
 * Category: security | Priority: critical
 * Verify page is served over HTTPS and redirects HTTP to HTTPS
 *
 * Source: http://localhost:5099/
 * Tags: security, https, tls
 * Auto-generated by Screener Playwright Crawler
 */

import { test, expect } from '@playwright/test';

test.describe('HTTPS enforcement', () => {

  test('HTTPS enforcement', async ({ page }) => {
    // Verify page is served over HTTPS and redirects HTTP to HTTPS
    await page.goto('http://localhost:5099/', { waitUntil: 'domcontentloaded' }); // HTTP requests redirect to HTTPS
    await expect(page).toHaveURL(/.*/);
    await page.goto('http://localhost:5099/', { waitUntil: 'domcontentloaded' }); // Final URL is HTTPS
    await expect(page).toHaveURL(/.*/);

    // Expected Results:
    // ✓ Page is served over HTTPS
    // ✓ HTTP requests are redirected to HTTPS
    // ✓ No mixed content warnings
    // ✓ HSTS header is present
  });
});
