/**
 * Sensitive data exposure check
 * Category: security | Priority: critical
 * Scan page source for exposed tokens, keys, or credentials
 *
 * Source: http://localhost:5099/
 * Tags: security, secrets, exposure
 * Auto-generated by Screener Playwright Crawler
 */

import { test, expect } from '@playwright/test';

test.describe('Sensitive data exposure check', () => {

  test('Sensitive data exposure check', async ({ page }) => {
    // Scan page source for exposed tokens, keys, or credentials
    await page.evaluate(() => { (() => {
            const html = document.documentElement.outerHTML;
            const patterns = [
              /sk-[a-zA-Z0-9]{20,}/,           // OpenAI/API keys
              /AIza[0-9A-Za-z_-]{35}/,         // Google API keys
              /-----BEGIN (RSA |EC )?PRIVATE KEY-----/,
              /ghp_[a-zA-Z0-9]{36}/,             // GitHub tokens
              /Bearer [A-Za-z0-9-._~+/]+=*/,     // Bearer tokens
              /passwords*[:=]s*['"][^'"]+['"]/i,
              /secrets*[:=]s*['"][^'"]+['"]/i,
              /api[_-]?keys*[:=]s*['"][^'"]+['"]/i,
            ];
            const found: string[] = [];
            for (const pattern of patterns) {
              const match = html.match(pattern);
              if (match) found.push(pattern.source.slice(0, 50));
            }
            return found.length > 0 ? JSON.stringify(found) : 'clean';
          })() }); // No API keys, tokens, or secrets in page source
    await expect(page.getByText('clean')).toBeVisible();

    // Expected Results:
    // ✓ No API keys in HTML source
    // ✓ No hardcoded passwords or secrets
    // ✓ No Bearer tokens in client-side code
    // ✓ No private keys exposed
  });
});
