/**
 * HTTPS enforcement
 * Category: security | Priority: critical
 * Verify page is served over HTTPS and redirects HTTP to HTTPS
 *
 * Source: https://demoqa.com/
 * Tags: security, https, tls
 * Auto-generated by Screener Playwright Crawler
 */

import { test, expect } from '@playwright/test';

test.describe('HTTPS enforcement', () => {

  test('HTTPS enforcement', async ({ page }) => {
    // Verify page is served over HTTPS and redirects HTTP to HTTPS
    await page.goto('http://demoqa.com/', { waitUntil: 'domcontentloaded' }); // HTTP requests redirect to HTTPS
    await expect(page).toHaveURL(/https://.*/);
    await page.goto('https://demoqa.com/', { waitUntil: 'domcontentloaded' }); // Final URL is HTTPS
    await expect(page).toHaveURL(/https://.*/);

    // Expected Results:
    // ✓ Page is served over HTTPS
    // ✓ HTTP requests are redirected to HTTPS
    // ✓ No mixed content warnings
    // ✓ HSTS header is present
  });
});
