/**
 * Form input labels (0 inputs)
 * Category: accessibility | Priority: critical
 * Verify all form inputs have associated labels
 *
 * Source: https://demoqa.com/
 * Tags: accessibility, labels, wcag-1.3
 * Auto-generated by Screener Playwright Crawler
 */

import { test, expect } from '@playwright/test';

test.describe('Form input labels (0 inputs)', () => {

  test('Form input labels (0 inputs)', async ({ page }) => {
    // Verify all form inputs have associated labels
    await page.goto('https://demoqa.com/', { waitUntil: 'domcontentloaded' }); // Page loaded
    await page.evaluate(() => { Array.from(document.querySelectorAll('input:not([type="hidden"]), select, textarea'))
          .filter(el => {
            if (el.getAttribute('aria-label') || el.getAttribute('aria-labelledby')) return false;
            if (el.id && document.querySelector(`label[for="${CSS.escape(el.id)}"]`)) return false;
            if (el.closest('label')) return false;
            return true;
          }).length }); // All inputs have accessible labels
    await expect(page.getByText('0')).toBeVisible();

    // Expected Results:
    // ✓ Every form input has a label (explicit or implicit)
    // ✓ Labels are descriptive and unique where appropriate
    // ✓ Placeholder text is not used as sole label
  });
});
