/**
 * Image alt text check (0 images)
 * Category: accessibility | Priority: critical
 * Verify all images have appropriate alt text
 *
 * Source: https://demoqa.com/
 * Tags: accessibility, images, wcag-1.1
 * Auto-generated by Screener Playwright Crawler
 */

import { test, expect } from '@playwright/test';

test.describe('Image alt text check (0 images)', () => {

  test('Image alt text check (0 images)', async ({ page }) => {
    // Verify all images have appropriate alt text
    await page.goto('https://demoqa.com/', { waitUntil: 'domcontentloaded' }); // Page loaded
    await page.evaluate(() => { Array.from(document.querySelectorAll('img')).filter(i => !i.alt).length }); // All images have alt attributes
    await expect(page.getByText('0')).toBeVisible();
    await page.evaluate(() => { Array.from(document.querySelectorAll('img[alt=""]')).length }); // Decorative images use empty alt=""

    // Expected Results:
    // ✓ All <img> elements have alt attribute
    // ✓ Informational images have descriptive alt text
    // ✓ Decorative images use alt=""
    // ✓ No images with filename as alt text
  });
});
