/**
 * Heading structure (H1:0 H2:0 H3:0)
 * Category: accessibility | Priority: high
 * Verify heading hierarchy follows WCAG guidelines
 *
 * Source: https://demoqa.com/
 * Tags: accessibility, headings, wcag-1.3
 * Auto-generated by Screener Playwright Crawler
 */

import { test, expect } from '@playwright/test';

test.describe('Heading structure (H1:0 H2:0 H3:0)', () => {

  test('Heading structure (H1:0 H2:0 H3:0)', async ({ page }) => {
    // Verify heading hierarchy follows WCAG guidelines
    await page.goto('https://demoqa.com/', { waitUntil: 'domcontentloaded' }); // Page loaded
    await page.evaluate(() => { document.querySelectorAll("h1").length }); // Page has exactly one H1
    await expect(page.getByText('1')).toBeVisible();
    await page.evaluate(() => { (() => {
            const headings = [...document.querySelectorAll("h1,h2,h3,h4,h5,h6")];
            let prev = 0;
            for (const h of headings) {
              const lvl = parseInt(h.tagName[1]);
              if (prev > 0 && lvl > prev + 1) return false;
              prev = lvl;
            }
            return true;
          })() }); // No heading levels skipped
    await expect(page.getByText('true')).toBeVisible();

    // Expected Results:
    // ✓ One H1 per page
    // ✓ Headings are sequential (no skipped levels)
    // ✓ Headings accurately describe content structure
  });
});
