/**
 * Keyboard navigation accessibility
 * Category: accessibility | Priority: high
 * Verify all interactive elements are reachable via keyboard (Tab/Shift+Tab)
 *
 * Source: http://localhost:5099/
 * Tags: accessibility, keyboard, wcag-2.1
 * Auto-generated by Screener Playwright Crawler
 */

import { test, expect } from '@playwright/test';

test.describe('Keyboard navigation accessibility', () => {

  test('Keyboard navigation accessibility', async ({ page }) => {
    // Verify all interactive elements are reachable via keyboard (Tab/Shift+Tab)
    await page.goto('http://localhost:5099/', { waitUntil: 'domcontentloaded' }); // Page loaded
    await page.locator('body').press('Tab'); // First focusable element receives focus
    await page.locator('body').press('Tab'); // Focus moves forward to next element
    await page.locator('body').press('Enter'); // Focused element activates on Enter
    await page.locator('body').press('Escape'); // Escape dismisses overlays/menus

    // Expected Results:
    // ✓ All interactive elements are keyboard-reachable
    // ✓ Focus indicator is visible
    // ✓ Tab order follows logical reading order
    // ✓ Enter/Space activates focused elements
    // ✓ Escape closes modals/dropdowns
  });
});
