/**
 * Full-page screenshot comparison
 * Category: visual | Priority: medium
 * Capture full-page screenshot for visual regression baseline
 *
 * Source: https://demoqa.com/
 * Tags: visual, screenshot, regression
 * Auto-generated by Screener Playwright Crawler
 */

import { test, expect } from '@playwright/test';

test.describe('Full-page screenshot comparison', () => {

  test('Full-page screenshot comparison', async ({ page }) => {
    // Capture full-page screenshot for visual regression baseline
    await page.goto('https://demoqa.com/', { waitUntil: 'domcontentloaded' }); // Page loaded
    await page.screenshot({ fullPage: true, path: 'screenshots/visual-fullpage-https-demoqa-com-.png' }); // Full-page screenshot captured as baseline

    // Expected Results:
    // ✓ Full-page screenshot captured successfully
    // ✓ No visual anomalies (blank areas, broken images)
    // ✓ Can be used for future visual diff comparisons
  });
});
