/**
 * Responsive layout: desktop (1440×900)
 * Category: visual | Priority: high
 * Verify page renders correctly at desktop viewport
 *
 * Source: http://localhost:5099/
 * Tags: visual, responsive, desktop
 * Auto-generated by Screener Playwright Crawler
 */

import { test, expect } from '@playwright/test';

test.describe('Responsive layout: desktop (1440×900)', () => {

  test('Responsive layout: desktop (1440×900)', async ({ page }) => {
    // Verify page renders correctly at desktop viewport
    await page.goto('http://localhost:5099/', { waitUntil: 'domcontentloaded' }); // Page loaded at desktop viewport
    await page.evaluate(() => { window.innerWidth === 1440 && window.innerHeight === 900 }); // Viewport is 1440×900
    await expect(page.getByText('true')).toBeVisible();
    await page.screenshot({ fullPage: true, path: 'screenshots/visual-viewport-desktop-http-localhost-5099-.png' }); // Screenshot captured: desktop
    await page.evaluate(() => { (() => {
            const body = document.body;
            const html = document.documentElement;
            const hasHorizontalScroll = html.scrollWidth > html.clientWidth;
            const hasOverflow = body.scrollWidth > body.clientWidth;
            return !hasHorizontalScroll && !hasOverflow;
          })() }); // No horizontal scrollbar
    await expect(page.getByText('true')).toBeVisible();
    await page.locator('footer, body > *:last-child').scrollIntoViewIfNeeded(); // Footer/last element reachable

    // Expected Results:
    // ✓ Page renders without horizontal scroll at 1440px
    // ✓ All content is accessible without zooming
    // ✓ Navigation is usable (no hidden menus)
    // ✓ Text is readable at this width
  });
});
