/**
 * Responsive layout: wide (1920×1080)
 * Category: visual | Priority: high
 * Verify page renders correctly at wide viewport
 *
 * Source: http://localhost:5099/
 * Tags: visual, responsive, wide
 * Auto-generated by Screener Playwright Crawler
 */

import { test, expect } from '@playwright/test';

test.describe('Responsive layout: wide (1920×1080)', () => {

  test('Responsive layout: wide (1920×1080)', async ({ page }) => {
    // Verify page renders correctly at wide viewport
    await page.goto('http://localhost:5099/', { waitUntil: 'domcontentloaded' }); // Page loaded at wide viewport
    await page.evaluate(() => { window.innerWidth === 1920 && window.innerHeight === 1080 }); // Viewport is 1920×1080
    await expect(page.getByText('true')).toBeVisible();
    await page.screenshot({ fullPage: true, path: 'screenshots/visual-viewport-wide-http-localhost-5099-.png' }); // Screenshot captured: wide
    await page.evaluate(() => { (() => {
            const body = document.body;
            const html = document.documentElement;
            const hasHorizontalScroll = html.scrollWidth > html.clientWidth;
            const hasOverflow = body.scrollWidth > body.clientWidth;
            return !hasHorizontalScroll && !hasOverflow;
          })() }); // No horizontal scrollbar
    await expect(page.getByText('true')).toBeVisible();
    await page.locator('footer, body > *:last-child').scrollIntoViewIfNeeded(); // Footer/last element reachable

    // Expected Results:
    // ✓ Page renders without horizontal scroll at 1920px
    // ✓ All content is accessible without zooming
    // ✓ Navigation is usable (no hidden menus)
    // ✓ Text is readable at this width
  });
});
