/**
 * Layout integrity check
 * Category: visual | Priority: medium
 * Verify no overlapping, clipping, or overflow issues
 *
 * Source: http://localhost:5099/
 * Tags: visual, layout, overflow
 * Auto-generated by Screener Playwright Crawler
 */

import { test, expect } from '@playwright/test';

test.describe('Layout integrity check', () => {

  test('Layout integrity check', async ({ page }) => {
    // Verify no overlapping, clipping, or overflow issues
    await page.goto('http://localhost:5099/', { waitUntil: 'domcontentloaded' }); // Page loaded for layout check
    await page.evaluate(() => { (() => {
            const body = document.body;
            const hasOverflowX = body.scrollWidth > body.clientWidth;
            const fixedElements = document.querySelectorAll('[style*="position: fixed"], [style*="position:fixed"]');
            const visibleFixed = Array.from(fixedElements).filter(el => {
              const style = window.getComputedStyle(el);
              return style.display !== 'none' && style.visibility !== 'hidden';
            });
            return { hasOverflowX, fixedCount: visibleFixed.length };
          })() }); // Layout structure analyzed
    await page.evaluate(() => { (() => {
            const sections = document.querySelectorAll('nav, header, main, footer, section, aside, [role="main"]');
            let overlaps = 0;
            for (let i = 0; i < sections.length; i++) {
              const a = sections[i].getBoundingClientRect();
              for (let j = i + 1; j < sections.length; j++) {
                const b = sections[j].getBoundingClientRect();
                if (a.width === 0 || a.height === 0 || b.width === 0 || b.height === 0) continue;
                const overlap = !(a.right <= b.left || a.left >= b.right || a.bottom <= b.top || a.top >= b.bottom);
                if (overlap) overlaps++;
              }
            }
            return overlaps;
          })() }); // No major layout sections overlap
    await expect(page.getByText('0')).toBeVisible();

    // Expected Results:
    // ✓ No horizontal overflow
    // ✓ Fixed elements do not overlap content
    // ✓ Sections are properly separated
    // ✓ Content does not overflow its containers
  });
});
