/**
 * Responsive layout: mobile (375×812)
 * Category: visual | Priority: high
 * Verify page renders correctly at mobile viewport
 *
 * Source: https://demoqa.com/
 * Tags: visual, responsive, mobile
 * Auto-generated by Screener Playwright Crawler
 */

import { test, expect } from '@playwright/test';

test.describe('Responsive layout: mobile (375×812)', () => {

  test('Responsive layout: mobile (375×812)', async ({ page }) => {
    // Verify page renders correctly at mobile viewport
    await page.goto('https://demoqa.com/', { waitUntil: 'domcontentloaded' }); // Page loaded at mobile viewport
    await page.evaluate(() => { window.innerWidth === 375 && window.innerHeight === 812 }); // Viewport is 375×812
    await expect(page.getByText('true')).toBeVisible();
    await page.screenshot({ fullPage: true, path: 'screenshots/visual-viewport-mobile-https-demoqa-com-.png' }); // Screenshot captured: mobile
    await page.evaluate(() => { (() => {
            const body = document.body;
            const html = document.documentElement;
            const hasHorizontalScroll = html.scrollWidth > html.clientWidth;
            const hasOverflow = body.scrollWidth > body.clientWidth;
            return !hasHorizontalScroll && !hasOverflow;
          })() }); // No horizontal scrollbar
    await expect(page.getByText('true')).toBeVisible();
    await page.locator('footer, body > *:last-child').scrollIntoViewIfNeeded(); // Footer/last element reachable

    // Expected Results:
    // ✓ Page renders without horizontal scroll at 375px
    // ✓ All content is accessible without zooming
    // ✓ Navigation is usable (no hidden menus)
    // ✓ Text is readable at this width
  });
});
