/**
 * Responsive layout: tablet (768×1024)
 * Category: visual | Priority: high
 * Verify page renders correctly at tablet viewport
 *
 * Source: http://localhost:5099/
 * Tags: visual, responsive, tablet
 * Auto-generated by Screener Playwright Crawler
 */

import { test, expect } from '@playwright/test';

test.describe('Responsive layout: tablet (768×1024)', () => {

  test('Responsive layout: tablet (768×1024)', async ({ page }) => {
    // Verify page renders correctly at tablet viewport
    await page.goto('http://localhost:5099/', { waitUntil: 'domcontentloaded' }); // Page loaded at tablet viewport
    await page.evaluate(() => { window.innerWidth === 768 && window.innerHeight === 1024 }); // Viewport is 768×1024
    await expect(page.getByText('true')).toBeVisible();
    await page.screenshot({ fullPage: true, path: 'screenshots/visual-viewport-tablet-http-localhost-5099-.png' }); // Screenshot captured: tablet
    await page.evaluate(() => { (() => {
            const body = document.body;
            const html = document.documentElement;
            const hasHorizontalScroll = html.scrollWidth > html.clientWidth;
            const hasOverflow = body.scrollWidth > body.clientWidth;
            return !hasHorizontalScroll && !hasOverflow;
          })() }); // No horizontal scrollbar
    await expect(page.getByText('true')).toBeVisible();
    await page.locator('footer, body > *:last-child').scrollIntoViewIfNeeded(); // Footer/last element reachable

    // Expected Results:
    // ✓ Page renders without horizontal scroll at 768px
    // ✓ All content is accessible without zooming
    // ✓ Navigation is usable (no hidden menus)
    // ✓ Text is readable at this width
  });
});
