/**
 * Page loads successfully: demosite
 * Category: functional | Priority: critical
 * Verify https://demoqa.com/ loads with correct title and content
 *
 * Source: https://demoqa.com/
 * Tags: smoke, page-load
 * Auto-generated by Screener Playwright Crawler
 */

import { test, expect } from '@playwright/test';

test.describe('Page loads successfully: demosite', () => {

  test('Page loads successfully: demosite', async ({ page }) => {
    // Verify https://demoqa.com/ loads with correct title and content
    await page.goto('https://demoqa.com/', { waitUntil: 'domcontentloaded' }); // Page title matches
    await expect(page).toHaveTitle(/demosite/);
    await page.waitForSelector('body', { timeout: 5000 }); // Body is visible
    await expect(page.locator('body')).toBeVisible({ timeout: 5000 });

    // Expected Results:
    // ✓ Page loads without errors
    // ✓ Title contains "demosite"
    // ✓ No console errors
    // ✓ Content is visible
  });
});
