/**
 * Page loads successfully: Nifty Signal
 * Category: functional | Priority: critical
 * Verify http://localhost:5099/ loads with correct title and content
 *
 * Source: http://localhost:5099/
 * Tags: smoke, page-load
 * Auto-generated by Screener Playwright Crawler
 */

import { test, expect } from '@playwright/test';

test.describe('Page loads successfully: Nifty Signal', () => {

  test('Page loads successfully: Nifty Signal', async ({ page }) => {
    // Verify http://localhost:5099/ loads with correct title and content
    await page.goto('http://localhost:5099/', { waitUntil: 'domcontentloaded' }); // Page title matches
    await expect(page).toHaveTitle(/Nifty Signal/);
    await page.waitForSelector('body', { timeout: 5000 }); // Body is visible
    await expect(page.locator('body')).toBeVisible({ timeout: 5000 });

    // Expected Results:
    // ✓ Page loads without errors
    // ✓ Title contains "Nifty Signal"
    // ✓ No console errors
    // ✓ Content is visible
  });
});
