// test-writer.ts — Write generated tests to categorized directories

import { GeneratedTest } from './types';
import * as fs from 'fs';
import * as path from 'path';

const CATEGORY_DIRS: Record<string, string> = {
  functional: 'functional',
  negative: 'negative',
  boundary: 'boundary',
  accessibility: 'accessibility',
  visual: 'visual',
  security: 'security',
};

export class TestWriter {
  private outputDir: string;
  private stats: Record<string, number> = {};

  constructor(outputDir: string) {
    this.outputDir = outputDir;
    // Ensure directories exist
    for (const dir of Object.values(CATEGORY_DIRS)) {
      fs.mkdirSync(path.join(outputDir, dir), { recursive: true });
    }
  }

  /**
   * Write a generated test to its category directory as a Playwright spec
   */
  write(test: GeneratedTest): string {
    const categoryDir = CATEGORY_DIRS[test.category] || 'functional';
    const dirPath = path.join(this.outputDir, categoryDir);
    const fileName = `${test.id}.spec.ts`;
    const filePath = path.join(dirPath, fileName);

    const content = this.generatePlaywrightSpec(test);
    fs.writeFileSync(filePath, content, 'utf-8');

    this.stats[test.category] = (this.stats[test.category] || 0) + 1;
    return filePath;
  }

  /**
   * Write all tests from an array
   */
  writeAll(tests: GeneratedTest[]): void {
    for (const test of tests) {
      this.write(test);
    }
  }

  /**
   * Get write statistics
   */
  getStats(): Record<string, number> {
    return { ...this.stats };
  }

  /**
   * Generate a Playwright test spec from a GeneratedTest
   */
  private generatePlaywrightSpec(test: GeneratedTest): string {
    const lines: string[] = [
      `/**`,
      ` * ${test.name}`,
      ` * Category: ${test.category} | Priority: ${test.priority}`,
      ` * ${test.description}`,
      ` *`,
      ` * Source: ${test.sourcePage}`,
      ` * Tags: ${test.tags.join(', ')}`,
      ` * Auto-generated by Screener Playwright Crawler`,
      ` */`,
      ``,
      `import { test, expect } from '@playwright/test';`,
      ``,
      `test.describe('${this.escapeJsString(test.name)}', () => {`,
      ``,
    ];

    // Add test case
    lines.push(`  test('${this.escapeJsString(test.name)}', async ({ page }) => {`);
    lines.push(`    // ${test.description}`);

    for (const step of test.steps) {
      const comment = step.assertion.description
        ? ` // ${step.assertion.description}`
        : '';

      switch (step.action) {
        case 'goto':
          lines.push(`    await page.goto('${this.escapeJsString(step.target || '')}', { waitUntil: 'domcontentloaded' });${comment}`);
          break;
        case 'click':
          if (step.target) {
            lines.push(`    await page.click('${this.escapeJsString(step.target)}');${comment}`);
          }
          break;
        case 'fill':
          if (step.target) {
            lines.push(`    await page.fill('${this.escapeJsString(step.target)}', '${this.escapeJsString(step.value || '')}');${comment}`);
          }
          break;
        case 'selectOption':
          if (step.target) {
            lines.push(`    await page.selectOption('${this.escapeJsString(step.target)}', '${this.escapeJsString(step.value || '')}');${comment}`);
          }
          break;
        case 'check':
          if (step.target) {
            lines.push(`    await page.check('${this.escapeJsString(step.target)}');${comment}`);
          }
          break;
        case 'uncheck':
          if (step.target) {
            lines.push(`    await page.uncheck('${this.escapeJsString(step.target)}');${comment}`);
          }
          break;
        case 'pressKey':
          const target = step.target || 'body';
          lines.push(`    await page.locator('${this.escapeJsString(target)}').press('${this.escapeJsString(step.value || 'Enter')}');${comment}`);
          break;
        case 'hover':
          if (step.target) {
            lines.push(`    await page.hover('${this.escapeJsString(step.target)}');${comment}`);
          }
          break;
        case 'waitForSelector':
          if (step.target) {
            lines.push(`    await page.waitForSelector('${this.escapeJsString(step.target)}', { timeout: ${step.timeoutMs} });${comment}`);
          }
          break;
        case 'waitForNavigation':
          lines.push(`    await page.waitForLoadState('networkidle');${comment}`);
          break;
        case 'screenshot':
          lines.push(`    await page.screenshot({ fullPage: true, path: 'screenshots/${test.id}.png' });${comment}`);
          break;
        case 'evaluate':
          lines.push(`    await page.evaluate(() => { ${step.value || '/* evaluation */'} });${comment}`);
          break;
        case 'scrollIntoView':
          if (step.target) {
            lines.push(`    await page.locator('${this.escapeJsString(step.target)}').scrollIntoViewIfNeeded();${comment}`);
          }
          break;
        default:
          lines.push(`    // Action: ${step.action} - ${comment}`);
      }

      // Add assertion
      if (step.assertion) {
        lines.push(...this.generateAssertion(step.assertion, '    '));
      }
    }

    // Expected results as comments
    lines.push('');
    lines.push('    // Expected Results:');
    for (const result of test.expectedResults) {
      lines.push(`    // ✓ ${result}`);
    }

    lines.push('  });');
    lines.push('});');
    lines.push('');

    return lines.join('\n');
  }

  /**
   * Generate Playwright expect() statements from assertion
   */
  private generateAssertion(assertion: any, indent: string): string[] {
    const lines: string[] = [];

    switch (assertion.type) {
      case 'visible':
        if (assertion.target) {
          lines.push(`${indent}await expect(page.locator('${this.escapeJsString(assertion.target)}')).toBeVisible({ timeout: 5000 });`);
        }
        break;
      case 'hidden':
        if (assertion.target) {
          lines.push(`${indent}await expect(page.locator('${this.escapeJsString(assertion.target)}')).toBeHidden({ timeout: 5000 });`);
        }
        break;
      case 'text':
        if (assertion.expected) {
          lines.push(`${indent}await expect(page.getByText('${this.escapeJsString(String(assertion.expected))}')).toBeVisible();`);
        }
        break;
      case 'value':
        if (assertion.target && assertion.expected) {
          lines.push(`${indent}await expect(page.locator('${this.escapeJsString(assertion.target)}')).toHaveValue('${this.escapeJsString(String(assertion.expected))}');`);
        }
        break;
      case 'url':
        if (assertion.expected) {
          const urlPattern = String(assertion.expected).replace(/\*/g, '.*');
          if (urlPattern.includes('.*')) {
            lines.push(`${indent}await expect(page).toHaveURL(/${urlPattern}/);`);
          } else {
            lines.push(`${indent}await expect(page).toHaveURL('${this.escapeJsString(urlPattern)}');`);
          }
        }
        break;
      case 'title':
        if (assertion.expected) {
          lines.push(`${indent}await expect(page).toHaveTitle(/${this.escapeJsString(String(assertion.expected))}/);`);
        }
        break;
      case 'enabled':
        if (assertion.target) {
          lines.push(`${indent}await expect(page.locator('${this.escapeJsString(assertion.target)}')).toBeEnabled();`);
        }
        break;
      case 'disabled':
        if (assertion.target) {
          lines.push(`${indent}await expect(page.locator('${this.escapeJsString(assertion.target)}')).toBeDisabled();`);
        }
        break;
      case 'checked':
        if (assertion.target) {
          lines.push(`${indent}await expect(page.locator('${this.escapeJsString(assertion.target)}')).toBeChecked();`);
        }
        break;
      case 'count':
        if (assertion.target && assertion.expected) {
          lines.push(`${indent}await expect(page.locator('${this.escapeJsString(assertion.target)}')).toHaveCount(${assertion.expected});`);
        }
        break;
      case 'focused':
        if (assertion.target) {
          lines.push(`${indent}await expect(page.locator('${this.escapeJsString(assertion.target)}')).toBeFocused();`);
        }
        break;
      default:
        lines.push(`${indent}// Assertion: ${assertion.description || assertion.type}`);
    }

    return lines;
  }

  /**
   * Escape a string for safe JS string literal use
   */
  private escapeJsString(str: string): string {
    return str
      .replace(/\\/g, '\\\\')
      .replace(/'/g, "\\'")
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r');
  }
}
