/**
 * No console errors on page load
 * Category: negative | Priority: high
 * Verify page loads without JavaScript errors in console
 *
 * Source: https://demoqa.com/
 * Tags: negative, errors, console
 * Auto-generated by Screener Playwright Crawler
 */

import { test, expect } from '@playwright/test';

test.describe('No console errors on page load', () => {

  test('No console errors on page load', async ({ page }) => {
    // Verify page loads without JavaScript errors in console
    await page.goto('https://demoqa.com/', { waitUntil: 'domcontentloaded' }); // No console errors detected

    // Expected Results:
    // ✓ Zero console errors
    // ✓ No 404s for critical resources
  });
});
